### ISSUE TITLE
上传出现413错误

### ISSUE THREAD

**Issue by Zertu** [comwrg/bilibiliUpload#10]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<h1>413 Request Entity Too Large</h1>
<P>The requested resource does not allow request data with the requested method or the amount of data provided in the request exceeds the capacity limit. Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>http://upcdn-bsy.acgvideo.com/vs101/upload3/ee98fb1c21d27ed75433d328da6db0ce/?uid=1831815&amp;filename=g180122011tirztrqq0k25ep72lr6szc&amp;deadline=1516776972&amp;profile=ugcfr%2Fweb3&amp;os=bili&amp;upcdn=bsy&amp;tag=&amp;uip=60.205.226.218&amp;uploadstart=1516632972</td>
</tr>
<tr>
<td>Server:</td>
<td>hzsq-bvc-slb-03</td>
</tr>
<tr>
<td>Date:</td>
<td>2018/01/22 22:58:48</td>
</tr>
</table>
<hr/>Powered by Tengine</body>
</html>

**Comment by comwrg** [comment]
上传的视频太大？你试试小的可不可以上传

**Comment by Zertu** [comment]
话说作者能不能讲一下desc这个参数是干嘛的啊。。

**Comment by comwrg** [comment]
title是上传视频的标题
desc是上传视频的描述
