### ISSUE TITLE
传输发生错误

### ISSUE THREAD

**Issue by a1928370421** [comwrg/bilibiliUpload#11]
requests.exceptions.ConnectionError: ('Connection aborted.', error(32, 'Broken pipe'))

**Comment by a1928370421** [comment]
程序传这个请求时出现错误         r = self.session.post(url_complete,
                              data={
                                  'name'    : filename,
                                  'chunks'  : chunks_num,
                                  'filesize': filesize,
                                  'csrf'    : self.csrf
                              },
                              headers={
                                  'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
                              })
      返回了 “param chunks required”

**Comment by comwrg** [comment]
登录成功了吗
完整的代码贴出来

**Comment by comwrg** [comment]
tid是视频的类别

https://member.bilibili.com/x/web/archive/pre

这个地址里有， JSON格式下看

**Comment by a1928370421** [comment]
谢谢 问一下如果想设置多个tag怎么做

**Comment by comwrg** [comment]
刚修复了， 用list

**Comment by a1928370421** [comment]
{"code":21013,"message":"第(1)个视频的标题有违禁符号，只能由中文、英文、数字、日文等可见字符组成","ttl":1}
            还发现一个问题我在最后submit的时候出错了 
            title=re.sub('[^a-zA-Z0-9]',' ',title)
            title=title[0:80]
            对标题过滤特殊字符
之后还是报错{"code":21013,"message":"第(1)个视频的标题有违禁符号，只能由中文、英文、数字、日文等可见字符组成","ttl":1}

**Comment by comwrg** [comment]
你标题是啥

**Comment by a1928370421** [comment]
我把你的那个tag=“，”.join（tag）去掉就好了。。。
