### ISSUE TITLE
文件上传接口好像有问题，提示Filesize required

### ISSUE THREAD

**Issue by Ayppo** [comwrg/bilibiliUpload#15]
`print response.text, chunk_num, chunk_index`
输出：
{"OK":0,"info":"Filesize required."} 7.0 1

**Comment by comwrg** [comment]
我这里上传并没有出现， 可以提供更详细的信息吗？

**Comment by Ayppo** [comment]
噢，是我自己的问题。
python2.7环境下`chunks_num = math.ceil(filesize / CHUNK_SIZE)` 需要改为 `chunks_num = math.ceil(filesize * 1.0 / CHUNK_SIZE)`，不然当filesize < CHUNK_SIZE的时候会报错

**Comment by Ayppo** [comment]
另外一个问题：
脚本投稿半天了一直在审核。然后在这期间，我手动投稿一次信息完全相同的视频，半小时就过审了。。。不太清楚到底哪个流程有问题，目前还没找到原因。。。

**Comment by comwrg** [comment]
这个我以前遇到过， 应该是视频没有上传完整， 导致转码失败这样。可能是接口的问题吧， 需要具体研究一下

**Comment by thinkqob** [comment]
> 恩，我发现现在b站的上传接口跟你这个有些不一样，用那个重写之后就可以上传并通过审核了。

请问是怎么重写的，我也遇到了，上传后一直是审核的状态。

**Comment by comwrg** [comment]
用的是最新的版本吗

最新版我之前测试时OK的

**Comment by comwrg** [comment]
> > 用的是最新的版本吗 最新版我之前测试时OK的
> > 是pip安装的，今天又试了一下，同样手动上传的就可以通过审核。

试下最新版, 今天修复了

**Comment by comwrg** [comment]
> > > > 用的是最新的版本吗 最新版我之前测试时OK的
> > > > 是pip安装的，今天又试了一下，同样手动上传的就可以通过审核。
> > 
> > 
> > 试下最新版, 今天修复了
> 
> 可以了，感谢。
> 另外文档里面关于tid的说明连接https://member.bilibili.com/x/web/archive/pre 已经失效了，找到了这个https://github.com/uupers/BiliSpider/wiki/%E8%A7%86%E9%A2%91%E5%88%86%E5%8C%BA%E5%AF%B9%E5%BA%94%E8%A1%A8

好,感谢
