### ISSUE TITLE
上传字幕

### ISSUE THREAD

**Issue by deng47** [comwrg/bilibiliupload#17]
不知道有没有了解过b站最近新添加的上传字幕功能？我正在尝试把youtube下载的字幕上传到b站，可惜遇到了一些难题。如果方便，可以看看吗？https://github.com/deng47/JOQR2Bilibili 谢谢

**Comment by deng47** [comment]
请问能否提供多一点提示？谢谢

**Comment by comwrg** [comment]
怎么投稿字幕？

**Comment by comwrg** [comment]
嗯， 现在遇到了什么问题？

**Comment by comwrg** [comment]
HTTP抓包照着写就可以了， 然后看返回信息， 慢慢调

**Comment by comwrg** [comment]
哈，没事
