### ISSUE TITLE
有没有demo

### ISSUE THREAD

**Issue by ZhangMingZhao1** [comwrg/bilibiliupload#18]

**Comment by sqy941013** [comment]
from bilibiliupload import *

b = Bilibili()

login_status = b.login('username@user.com', 'password')
print("Login:", login_status)

videoPart = VideoPart('153.mp4', 'this is 153 desc')

tags = {u"123", u"Shroud", u"Beaulo"}

b.upload(parts=videoPart, title='153 title', tid=65, tag=tags, desc='Uploaded from 23333',
         source='http://www.youtube.com')




这个是我测试用的一个程序，可以上传视频。但是没法上传封面。
{"code":21008,"message":"封面必须由页面进行上传，不支持外部链接","ttl":1}

**Comment by ZhangMingZhao1** [comment]
cover呢，使用cover_up方法是什么意思
