### ISSUE TITLE
上传视频时出现OpenSSL的报错

### ISSUE THREAD

**Issue by ALENAVENGER** [comwrg/bilibiliupload#20]
报错信息
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert bad record mac')]
在源文件中的报错位置为调用 upload() 的地方
我的OpenSSL是 1.0.2 版本 还算比较新

PS：我一开始成功上传了一个小视频 但是之后想改写一下自己的脚本的功能，然后就出现这个问题了，把代码改回去也还是有这个问题

**Comment by ALENAVENGER** [comment]
我又试了一下 第一次我上传的是youtube-dl的测试视频 大小只有1786kb
而第之后尝试上传的是一个5分钟的介绍特斯拉的视频 大小是34932kb
当我把要上传的视频再次改回第一个小视频的时候，就又上传成功了
很迷……是对视频大小有限制么？但是现在网页端上最大都是8g啊

**Comment by comwrg** [comment]
可以的话, 视频发我邮箱(xcomwrg at gmail.com), 我来测试一下.

**Comment by ALENAVENGER** [comment]
这是我的测试视频和python脚本代码，我是在我自己的笔记本上运行，出现的报错。

comwrg <notifications@github.com> 于2019年2月24日周日 下午10:59写道：

**Comment by ALENAVENGER** [comment]
TKD.rar
<https://drive.google.com/file/d/1QEr_KNA-ykQIKQFn2z0q_CNJf19sGVTp/view?usp=drive_web>


Alen Chen <chenalenavenger@gmail.com> 于2019年3月12日周二 上午11:32写道：

**Comment by comwrg** [comment]
![image](https://user-images.githubusercontent.com/19854253/54256758-0142a080-4598-11e9-9462-4a68c06e5322.png)

![image](https://user-images.githubusercontent.com/19854253/54256781-17e8f780-4598-11e9-882a-84d66ba2f3a5.png)

我上传的代码
```
#! /usr/bin/env python3
# -*- coding: utf-8 -*-


from bilibiliupload import *

b = Bilibili()
r = b.login('username', 'password') ########### need replace
# if r is not True:
#     print(r)

r = b.upload(
        VideoPart('mp4 path', '1'),  ########### need replace
        'title2',
        28,
        ['tag'],
        '',
)





```
