### ISSUE TITLE
addChannel方法错误

### ISSUE THREAD

**Issue by Jaqen00** [comwrg/bilibiliupload#21]
首先感谢作者的代码，用起来很方便
在添加频道的时候出现错误，查看代码，发现添加频道的post请求是有问题的
这是我自己替换的代码，替换后添加成功
        r = self.session.post(
                url='https://api.bilibili.com/x/space/channel/add',
                data={
                    'name' : name,
                    'intro': intro,
                    'jsonp' : 'jsonp',
                    'csrf' : self.csrf,
                },

**Comment by comwrg** [comment]
非常感谢.

**Comment by Jaqen00** [comment]
还有channel_addVideo方法中的url应该是https://api.bilibili.com/x/space/channel/video/add
可能是bilibili改版了吧：）
