### ISSUE TITLE
多p视频Broken Pipe

### ISSUE THREAD

**Issue by Wszl** [comwrg/bilibiliupload#22]
上传多p视频时出现问题
9p, 每个文件大小在600m左右
大多数3p以下视频没有问题
env: Centos 7 
Python36 

``
publish on: 2019-03-14 18:30:00+08:06
login result:True
0/52 MULTIPART_PUT_SUCCESS
1/52 MULTIPART_PUT_SUCCESS
2/52 MULTIPART_PUT_SUCCESS
3/52 MULTIPART_PUT_SUCCESS
4/52 MULTIPART_PUT_SUCCESS
5/52 MULTIPART_PUT_SUCCESS
6/52 MULTIPART_PUT_SUCCESS
7/52 MULTIPART_PUT_SUCCESS
8/52 MULTIPART_PUT_SUCCESS
9/52 MULTIPART_PUT_SUCCESS
10/52 MULTIPART_PUT_SUCCESS
11/52 MULTIPART_PUT_SUCCESS
12/52 MULTIPART_PUT_SUCCESS
13/52 MULTIPART_PUT_SUCCESS
14/52 MULTIPART_PUT_SUCCESS
15/52 MULTIPART_PUT_SUCCESS
16/52 MULTIPART_PUT_SUCCESS
17/52 MULTIPART_PUT_SUCCESS
18/52 MULTIPART_PUT_SUCCESS
19/52 MULTIPART_PUT_SUCCESS
20/52 MULTIPART_PUT_SUCCESS
21/52 MULTIPART_PUT_SUCCESS
22/52 MULTIPART_PUT_SUCCESS
23/52 MULTIPART_PUT_SUCCESS
24/52 MULTIPART_PUT_SUCCESS
25/52 MULTIPART_PUT_SUCCESS
26/52 MULTIPART_PUT_SUCCESS
27/52 MULTIPART_PUT_SUCCESS
28/52 MULTIPART_PUT_SUCCESS
29/52 MULTIPART_PUT_SUCCESS
30/52 MULTIPART_PUT_SUCCESS
31/52 MULTIPART_PUT_SUCCESS
32/52 MULTIPART_PUT_SUCCESS
33/52 MULTIPART_PUT_SUCCESS
34/52 MULTIPART_PUT_SUCCESS
35/52 MULTIPART_PUT_SUCCESS
36/52 MULTIPART_PUT_SUCCESS
37/52 MULTIPART_PUT_SUCCESS
38/52 MULTIPART_PUT_SUCCESS
39/52 MULTIPART_PUT_SUCCESS
40/52 MULTIPART_PUT_SUCCESS
41/52 MULTIPART_PUT_SUCCESS
42/52 MULTIPART_PUT_SUCCESS
43/52 MULTIPART_PUT_SUCCESS
44/52 MULTIPART_PUT_SUCCESS
45/52 MULTIPART_PUT_SUCCESS
46/52 MULTIPART_PUT_SUCCESS
47/52 MULTIPART_PUT_SUCCESS
48/52 MULTIPART_PUT_SUCCESS
49/52 MULTIPART_PUT_SUCCESS
50/52 MULTIPART_PUT_SUCCESS
51/52 MULTIPART_PUT_SUCCESS
0/73 MULTIPART_PUT_SUCCESS
1/73 MULTIPART_PUT_SUCCESS
2/73 MULTIPART_PUT_SUCCESS
3/73 MULTIPART_PUT_SUCCESS
4/73 MULTIPART_PUT_SUCCESS
5/73 MULTIPART_PUT_SUCCESS
6/73 MULTIPART_PUT_SUCCESS
7/73 MULTIPART_PUT_SUCCESS
8/73 MULTIPART_PUT_SUCCESS
9/73 MULTIPART_PUT_SUCCESS
10/73 MULTIPART_PUT_SUCCESS
11/73 MULTIPART_PUT_SUCCESS
12/73 MULTIPART_PUT_SUCCESS
13/73 MULTIPART_PUT_SUCCESS
14/73 MULTIPART_PUT_SUCCESS
15/73 MULTIPART_PUT_SUCCESS
16/73 MULTIPART_PUT_SUCCESS
17/73 MULTIPART_PUT_SUCCESS
18/73 MULTIPART_PUT_SUCCESS
19/73 MULTIPART_PUT_SUCCESS
20/73 MULTIPART_PUT_SUCCESS
21/73 MULTIPART_PUT_SUCCESS
22/73 MULTIPART_PUT_SUCCESS
23/73 MULTIPART_PUT_SUCCESS
24/73 MULTIPART_PUT_SUCCESS
25/73 MULTIPART_PUT_SUCCESS
26/73 MULTIPART_PUT_SUCCESS
27/73 MULTIPART_PUT_SUCCESS
28/73 MULTIPART_PUT_SUCCESS
29/73 MULTIPART_PUT_SUCCESS
30/73 MULTIPART_PUT_SUCCESS
31/73 MULTIPART_PUT_SUCCESS
32/73 MULTIPART_PUT_SUCCESS
33/73 MULTIPART_PUT_SUCCESS
34/73 MULTIPART_PUT_SUCCESS
35/73 MULTIPART_PUT_SUCCESS
36/73 MULTIPART_PUT_SUCCESS
37/73 MULTIPART_PUT_SUCCESS
38/73 MULTIPART_PUT_SUCCESS
39/73 MULTIPART_PUT_SUCCESS
40/73 MULTIPART_PUT_SUCCESS
41/73 MULTIPART_PUT_SUCCESS
42/73 MULTIPART_PUT_SUCCESS
43/73 MULTIPART_PUT_SUCCESS
44/73 MULTIPART_PUT_SUCCESS
45/73 MULTIPART_PUT_SUCCESS
46/73 MULTIPART_PUT_SUCCESS
47/73 MULTIPART_PUT_SUCCESS
48/73 MULTIPART_PUT_SUCCESS
49/73 MULTIPART_PUT_SUCCESS
50/73 MULTIPART_PUT_SUCCESS
51/73 MULTIPART_PUT_SUCCESS
52/73 MULTIPART_PUT_SUCCESS
53/73 MULTIPART_PUT_SUCCESS
54/73 MULTIPART_PUT_SUCCESS
55/73 MULTIPART_PUT_SUCCESS
56/73 MULTIPART_PUT_SUCCESS
57/73 MULTIPART_PUT_SUCCESS
58/73 MULTIPART_PUT_SUCCESS
59/73 MULTIPART_PUT_SUCCESS
60/73 MULTIPART_PUT_SUCCESS
61/73 MULTIPART_PUT_SUCCESS
62/73 MULTIPART_PUT_SUCCESS
63/73 MULTIPART_PUT_SUCCESS
64/73 MULTIPART_PUT_SUCCESS
65/73 MULTIPART_PUT_SUCCESS
66/73 MULTIPART_PUT_SUCCESS
67/73 MULTIPART_PUT_SUCCESS
68/73 MULTIPART_PUT_SUCCESS
69/73 MULTIPART_PUT_SUCCESS
70/73 MULTIPART_PUT_SUCCESS
71/73 MULTIPART_PUT_SUCCESS
72/73 MULTIPART_PUT_SUCCESS
0/75 MULTIPART_PUT_SUCCESS
1/75 MULTIPART_PUT_SUCCESS
2/75 MULTIPART_PUT_SUCCESS
3/75 MULTIPART_PUT_SUCCESS
4/75 MULTIPART_PUT_SUCCESS
5/75 MULTIPART_PUT_SUCCESS
6/75 MULTIPART_PUT_SUCCESS
7/75 MULTIPART_PUT_SUCCESS
8/75 MULTIPART_PUT_SUCCESS
9/75 MULTIPART_PUT_SUCCESS
10/75 MULTIPART_PUT_SUCCESS
11/75 MULTIPART_PUT_SUCCESS
12/75 MULTIPART_PUT_SUCCESS
13/75 MULTIPART_PUT_SUCCESS
14/75 MULTIPART_PUT_SUCCESS
15/75 MULTIPART_PUT_SUCCESS
16/75 MULTIPART_PUT_SUCCESS
17/75 MULTIPART_PUT_SUCCESS
18/75 MULTIPART_PUT_SUCCESS
19/75 MULTIPART_PUT_SUCCESS
20/75 MULTIPART_PUT_SUCCESS
21/75 MULTIPART_PUT_SUCCESS
22/75 MULTIPART_PUT_SUCCESS
23/75 MULTIPART_PUT_SUCCESS
24/75 MULTIPART_PUT_SUCCESS
25/75 MULTIPART_PUT_SUCCESS
26/75 MULTIPART_PUT_SUCCESS
27/75 MULTIPART_PUT_SUCCESS
28/75 MULTIPART_PUT_SUCCESS
29/75 MULTIPART_PUT_SUCCESS
30/75 MULTIPART_PUT_SUCCESS
31/75 MULTIPART_PUT_SUCCESS
32/75 MULTIPART_PUT_SUCCESS
33/75 MULTIPART_PUT_SUCCESS
34/75 MULTIPART_PUT_SUCCESS
35/75 MULTIPART_PUT_SUCCESS
36/75 MULTIPART_PUT_SUCCESS
37/75 MULTIPART_PUT_SUCCESS
38/75 MULTIPART_PUT_SUCCESS
39/75 MULTIPART_PUT_SUCCESS
40/75 MULTIPART_PUT_SUCCESS
41/75 MULTIPART_PUT_SUCCESS
42/75 MULTIPART_PUT_SUCCESS
43/75 MULTIPART_PUT_SUCCESS
44/75 MULTIPART_PUT_SUCCESS
45/75 MULTIPART_PUT_SUCCESS
46/75 MULTIPART_PUT_SUCCESS
47/75 MULTIPART_PUT_SUCCESS
48/75 MULTIPART_PUT_SUCCESS
49/75 MULTIPART_PUT_SUCCESS
50/75 MULTIPART_PUT_SUCCESS
51/75 MULTIPART_PUT_SUCCESS
52/75 MULTIPART_PUT_SUCCESS
53/75 MULTIPART_PUT_SUCCESS
54/75 MULTIPART_PUT_SUCCESS
55/75 MULTIPART_PUT_SUCCESS
56/75 MULTIPART_PUT_SUCCESS
57/75 MULTIPART_PUT_SUCCESS
58/75 MULTIPART_PUT_SUCCESS
59/75 MULTIPART_PUT_SUCCESS
60/75 MULTIPART_PUT_SUCCESS
61/75 MULTIPART_PUT_SUCCESS
62/75 MULTIPART_PUT_SUCCESS
63/75 MULTIPART_PUT_SUCCESS
64/75 MULTIPART_PUT_SUCCESS
65/75 MULTIPART_PUT_SUCCESS
66/75 MULTIPART_PUT_SUCCESS
67/75 MULTIPART_PUT_SUCCESS
68/75 MULTIPART_PUT_SUCCESS
69/75 MULTIPART_PUT_SUCCESS
70/75 MULTIPART_PUT_SUCCESS
71/75 MULTIPART_PUT_SUCCESS
72/75 MULTIPART_PUT_SUCCESS
73/75 MULTIPART_PUT_SUCCESS
74/75 MULTIPART_PUT_SUCCESS
0/76 MULTIPART_PUT_SUCCESS
1/76 MULTIPART_PUT_SUCCESS
2/76 MULTIPART_PUT_SUCCESS
3/76 MULTIPART_PUT_SUCCESS
4/76 MULTIPART_PUT_SUCCESS
5/76 MULTIPART_PUT_SUCCESS
6/76 MULTIPART_PUT_SUCCESS
7/76 MULTIPART_PUT_SUCCESS
8/76 MULTIPART_PUT_SUCCESS
9/76 MULTIPART_PUT_SUCCESS
10/76 MULTIPART_PUT_SUCCESS
11/76 MULTIPART_PUT_SUCCESS
12/76 MULTIPART_PUT_SUCCESS
13/76 MULTIPART_PUT_SUCCESS
14/76 MULTIPART_PUT_SUCCESS
15/76 MULTIPART_PUT_SUCCESS
16/76 MULTIPART_PUT_SUCCESS
17/76 MULTIPART_PUT_SUCCESS
18/76 MULTIPART_PUT_SUCCESS
19/76 MULTIPART_PUT_SUCCESS
20/76 MULTIPART_PUT_SUCCESS
21/76 MULTIPART_PUT_SUCCESS
22/76 MULTIPART_PUT_SUCCESS
23/76 MULTIPART_PUT_SUCCESS
24/76 MULTIPART_PUT_SUCCESS
25/76 MULTIPART_PUT_SUCCESS
26/76 MULTIPART_PUT_SUCCESS
27/76 MULTIPART_PUT_SUCCESS
28/76 MULTIPART_PUT_SUCCESS
29/76 MULTIPART_PUT_SUCCESS
30/76 MULTIPART_PUT_SUCCESS
31/76 MULTIPART_PUT_SUCCESS
32/76 MULTIPART_PUT_SUCCESS
33/76 MULTIPART_PUT_SUCCESS
34/76 MULTIPART_PUT_SUCCESS
35/76 MULTIPART_PUT_SUCCESS
36/76 MULTIPART_PUT_SUCCESS
37/76 MULTIPART_PUT_SUCCESS
38/76 MULTIPART_PUT_SUCCESS
39/76 MULTIPART_PUT_SUCCESS
40/76 MULTIPART_PUT_SUCCESS
41/76 MULTIPART_PUT_SUCCESS
42/76 MULTIPART_PUT_SUCCESS
43/76 MULTIPART_PUT_SUCCESS
44/76 MULTIPART_PUT_SUCCESS
45/76 MULTIPART_PUT_SUCCESS
46/76 MULTIPART_PUT_SUCCESS
47/76 MULTIPART_PUT_SUCCESS
48/76 MULTIPART_PUT_SUCCESS
49/76 MULTIPART_PUT_SUCCESS
50/76 MULTIPART_PUT_SUCCESS
51/76 MULTIPART_PUT_SUCCESS
52/76 MULTIPART_PUT_SUCCESS
53/76 MULTIPART_PUT_SUCCESS
54/76 MULTIPART_PUT_SUCCESS
55/76 MULTIPART_PUT_SUCCESS
56/76 MULTIPART_PUT_SUCCESS
57/76 MULTIPART_PUT_SUCCESS
58/76 MULTIPART_PUT_SUCCESS
59/76 MULTIPART_PUT_SUCCESS
60/76 MULTIPART_PUT_SUCCESS
61/76 MULTIPART_PUT_SUCCESS
62/76 MULTIPART_PUT_SUCCESS
63/76 MULTIPART_PUT_SUCCESS
64/76 MULTIPART_PUT_SUCCESS
65/76 MULTIPART_PUT_SUCCESS
66/76 MULTIPART_PUT_SUCCESS
67/76 MULTIPART_PUT_SUCCESS
68/76 MULTIPART_PUT_SUCCESS
69/76 MULTIPART_PUT_SUCCESS
70/76 MULTIPART_PUT_SUCCESS
71/76 MULTIPART_PUT_SUCCESS
72/76 MULTIPART_PUT_SUCCESS
73/76 MULTIPART_PUT_SUCCESS
74/76 MULTIPART_PUT_SUCCESS
75/76 MULTIPART_PUT_SUCCESS
0/43 MULTIPART_PUT_SUCCESS
1/43 MULTIPART_PUT_SUCCESS
2/43 MULTIPART_PUT_SUCCESS
3/43 MULTIPART_PUT_SUCCESS
4/43 MULTIPART_PUT_SUCCESS
5/43 MULTIPART_PUT_SUCCESS
6/43 MULTIPART_PUT_SUCCESS
7/43 MULTIPART_PUT_SUCCESS
8/43 MULTIPART_PUT_SUCCESS
9/43 MULTIPART_PUT_SUCCESS
10/43 MULTIPART_PUT_SUCCESS
11/43 MULTIPART_PUT_SUCCESS
12/43 MULTIPART_PUT_SUCCESS
13/43 MULTIPART_PUT_SUCCESS
14/43 MULTIPART_PUT_SUCCESS
15/43 MULTIPART_PUT_SUCCESS
16/43 MULTIPART_PUT_SUCCESS
17/43 MULTIPART_PUT_SUCCESS
18/43 MULTIPART_PUT_SUCCESS
19/43 MULTIPART_PUT_SUCCESS
20/43 MULTIPART_PUT_SUCCESS
21/43 MULTIPART_PUT_SUCCESS
22/43 MULTIPART_PUT_SUCCESS
23/43 MULTIPART_PUT_SUCCESS
24/43 MULTIPART_PUT_SUCCESS
25/43 MULTIPART_PUT_SUCCESS
26/43 MULTIPART_PUT_SUCCESS
27/43 MULTIPART_PUT_SUCCESS
28/43 MULTIPART_PUT_SUCCESS
29/43 MULTIPART_PUT_SUCCESS
30/43 MULTIPART_PUT_SUCCESS
31/43 MULTIPART_PUT_SUCCESS
32/43 MULTIPART_PUT_SUCCESS
33/43 MULTIPART_PUT_SUCCESS
34/43 MULTIPART_PUT_SUCCESS
35/43 MULTIPART_PUT_SUCCESS
36/43 MULTIPART_PUT_SUCCESS
37/43 MULTIPART_PUT_SUCCESS
38/43 MULTIPART_PUT_SUCCESS
39/43 MULTIPART_PUT_SUCCESS
40/43 MULTIPART_PUT_SUCCESS
41/43 MULTIPART_PUT_SUCCESS
42/43 MULTIPART_PUT_SUCCESS
0/31 MULTIPART_PUT_SUCCESS
1/31 MULTIPART_PUT_SUCCESS
2/31 MULTIPART_PUT_SUCCESS
3/31 MULTIPART_PUT_SUCCESS
4/31 MULTIPART_PUT_SUCCESS
5/31 MULTIPART_PUT_SUCCESS
6/31 MULTIPART_PUT_SUCCESS
7/31 MULTIPART_PUT_SUCCESS
8/31 MULTIPART_PUT_SUCCESS
9/31 MULTIPART_PUT_SUCCESS
10/31 MULTIPART_PUT_SUCCESS
11/31 MULTIPART_PUT_SUCCESS
12/31 MULTIPART_PUT_SUCCESS
13/31 MULTIPART_PUT_SUCCESS
14/31 MULTIPART_PUT_SUCCESS
15/31 MULTIPART_PUT_SUCCESS
16/31 MULTIPART_PUT_SUCCESS
17/31 MULTIPART_PUT_SUCCESS
18/31 MULTIPART_PUT_SUCCESS
19/31 MULTIPART_PUT_SUCCESS
20/31 MULTIPART_PUT_SUCCESS
21/31 MULTIPART_PUT_SUCCESS
22/31 MULTIPART_PUT_SUCCESS
23/31 MULTIPART_PUT_SUCCESS
24/31 MULTIPART_PUT_SUCCESS
25/31 MULTIPART_PUT_SUCCESS
26/31 MULTIPART_PUT_SUCCESS
27/31 MULTIPART_PUT_SUCCESS
28/31 MULTIPART_PUT_SUCCESS
29/31 MULTIPART_PUT_SUCCESS
30/31 MULTIPART_PUT_SUCCESS
0/72 MULTIPART_PUT_SUCCESS
1/72 MULTIPART_PUT_SUCCESS
2/72 MULTIPART_PUT_SUCCESS
3/72 MULTIPART_PUT_SUCCESS
4/72 MULTIPART_PUT_SUCCESS
5/72 MULTIPART_PUT_SUCCESS
6/72 MULTIPART_PUT_SUCCESS
7/72 MULTIPART_PUT_SUCCESS
8/72 MULTIPART_PUT_SUCCESS
9/72 MULTIPART_PUT_SUCCESS
10/72 MULTIPART_PUT_SUCCESS
11/72 MULTIPART_PUT_SUCCESS
12/72 MULTIPART_PUT_SUCCESS
13/72 MULTIPART_PUT_SUCCESS
14/72 MULTIPART_PUT_SUCCESS
15/72 MULTIPART_PUT_SUCCESS
16/72 MULTIPART_PUT_SUCCESS
17/72 MULTIPART_PUT_SUCCESS
18/72 MULTIPART_PUT_SUCCESS
19/72 MULTIPART_PUT_SUCCESS
20/72 MULTIPART_PUT_SUCCESS
21/72 MULTIPART_PUT_SUCCESS
22/72 MULTIPART_PUT_SUCCESS
23/72 MULTIPART_PUT_SUCCESS
24/72 MULTIPART_PUT_SUCCESS
25/72 MULTIPART_PUT_SUCCESS
26/72 MULTIPART_PUT_SUCCESS
27/72 MULTIPART_PUT_SUCCESS
28/72 MULTIPART_PUT_SUCCESS
29/72 MULTIPART_PUT_SUCCESS
30/72 MULTIPART_PUT_SUCCESS
31/72 MULTIPART_PUT_SUCCESS
32/72 MULTIPART_PUT_SUCCESS
33/72 MULTIPART_PUT_SUCCESS
34/72 MULTIPART_PUT_SUCCESS
35/72 MULTIPART_PUT_SUCCESS
36/72 MULTIPART_PUT_SUCCESS
37/72 MULTIPART_PUT_SUCCESS
38/72 MULTIPART_PUT_SUCCESS
39/72 MULTIPART_PUT_SUCCESS
40/72 MULTIPART_PUT_SUCCESS
41/72 MULTIPART_PUT_SUCCESS
42/72 MULTIPART_PUT_SUCCESS
43/72 MULTIPART_PUT_SUCCESS
44/72 MULTIPART_PUT_SUCCESS
45/72 MULTIPART_PUT_SUCCESS
46/72 MULTIPART_PUT_SUCCESS
47/72 MULTIPART_PUT_SUCCESS
48/72 MULTIPART_PUT_SUCCESS
49/72 MULTIPART_PUT_SUCCESS
50/72 MULTIPART_PUT_SUCCESS
51/72 MULTIPART_PUT_SUCCESS
52/72 MULTIPART_PUT_SUCCESS
53/72 MULTIPART_PUT_SUCCESS
54/72 MULTIPART_PUT_SUCCESS
55/72 MULTIPART_PUT_SUCCESS
56/72 MULTIPART_PUT_SUCCESS
57/72 MULTIPART_PUT_SUCCESS
58/72 MULTIPART_PUT_SUCCESS
59/72 MULTIPART_PUT_SUCCESS
60/72 MULTIPART_PUT_SUCCESS
61/72 MULTIPART_PUT_SUCCESS
62/72 MULTIPART_PUT_SUCCESS
63/72 MULTIPART_PUT_SUCCESS
64/72 MULTIPART_PUT_SUCCESS
65/72 MULTIPART_PUT_SUCCESS
66/72 MULTIPART_PUT_SUCCESS
67/72 MULTIPART_PUT_SUCCESS
68/72 MULTIPART_PUT_SUCCESS
69/72 MULTIPART_PUT_SUCCESS
70/72 MULTIPART_PUT_SUCCESS
71/72 MULTIPART_PUT_SUCCESS
0/82 MULTIPART_PUT_SUCCESS
1/82 MULTIPART_PUT_SUCCESS
2/82 MULTIPART_PUT_SUCCESS
3/82 MULTIPART_PUT_SUCCESS
4/82 MULTIPART_PUT_SUCCESS
5/82 MULTIPART_PUT_SUCCESS
6/82 MULTIPART_PUT_SUCCESS
7/82 MULTIPART_PUT_SUCCESS
8/82 MULTIPART_PUT_SUCCESS
9/82 MULTIPART_PUT_SUCCESS
upload media failed by ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')).
update done media (datetime.datetime(2019, 3, 2, 4, 20, 53, 994766, tzinfo=<DstTzInfo 'Asia/Shanghai' CST+8:00:00 STD>), 'ERROR', "('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))", 725) success.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1065, in _send_output
    self.send(chunk)
  File "/usr/lib64/python3.6/http/client.py", line 986, in send
    self.sock.sendall(data)
  File "/usr/lib64/python3.6/ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib64/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/lib64/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./csgo_automatic_uploder.py", line 103, in <module>
    start()
  File "./csgo_automatic_uploder.py", line 73, in start
    raise e
  File "./csgo_automatic_uploder.py", line 69, in start
    publish_date)
  File "./csgo_automatic_uploder.py", line 99, in upload
    dtime=int(time.mktime(publish_date.timetuple()))
  File "/home/wszl/bin/csgo-group/bilibili.py", line 260, in upload
    chunks_data,
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 593, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BrokenPipeError(32, 'Broken pipe'))
``

**Comment by comwrg** [comment]
```
upload media failed by ('Connection aborted.', BrokenPipeError(32, 'Broken pipe')).
```
应该是TCP连接断了

可以加个重试机制试试

**Comment by Wszl** [comment]
第二次没问题了, 看来是tcp问题
