### ISSUE TITLE
动态以及视频简介

### ISSUE THREAD

**Issue by Kiritomo** [comwrg/bilibiliupload#39]
1.希望可以在上传的时候添加动态
2.视频简介长度250可以解决么？还是说服务限制的

**Comment by comwrg** [comment]
1.  上传视频页面最下方的粉丝动态吗？
2. B站限制

**Comment by Kiritomo** [comment]
是的，投稿页面下面的粉丝动态

**Comment by comwrg** [comment]
see v0.1.8

**Comment by Kiritomo** [comment]
已测试，暂未问题，但是我这边放在Linux上运行却报错了
  File "bilibili.py", line 181
    parts: Union[VideoPart, List[VideoPart]],
         ^
SyntaxError: invalid syntax

我这边是把我用到的代理直接写在bilibili.py里面直接运行，不知道是不是这问题

**Comment by comwrg** [comment]
给的信息太少，不清楚具体哪里有问题

日志打印：https://github.com/comwrg/bilibiliupload#why-not-log-print

**Comment by Kiritomo** [comment]
emmm,是我这边的失误，已经测试没有问题了，谢谢
