### ISSUE TITLE
极验问题

### ISSUE THREAD

**Issue by 2300206764** [comwrg/bilibiliUpload#4]
貌似我在本地测试现在百分百触发极验，而且获取access key的网站也是，返回都是验证码不通过，请问如何解决

**Comment by comwrg** [comment]
极验?

**Comment by 2300206764** [comment]
就是login操作的那个api百分百返回验证码错误的问题

**Comment by comwrg** [comment]
自己账号问题吧，我这里测试ok的

**Comment by comwrg** [comment]
你账号问题

2017-07-11 16:35 GMT+08:00 Box <notifications@github.com>:
