### ISSUE TITLE
"code":-449,"message":"服务繁忙, 请稍后再试"

### ISSUE THREAD

**Issue by qazwsdc** [comwrg/bilibiliupload#46]
login函数无法登录，
反复报错
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/bilibiliupload/bilibili.py", line 153, in login
    raise Exception(r.text)
Exception: {"code":-449,"message":"服务繁忙, 请稍后再试","ts":1576833394}

**Comment by andyhuzhill** [comment]
这个更新一下版本就解决了吧  你报bug也写一下版本吧

**Comment by qazwsdc** [comment]
我用的的确是最新版
我试了下是下面这个验证码识别的url无法访问了：
http://47.95.255.188:5000/code

**Comment by wwng2333** [comment]
怀疑跟IP有关 我在2个linode上跑 都返回
`Exception:` {"code":-449,"message":"服务繁忙, `请稍后再试","ts":1586099931}`
