### ISSUE TITLE
关于推荐标签

### ISSUE THREAD

**Issue by Kiritomo** [comwrg/bilibiliupload#47]
希望可以加入自动使用推荐标签的功能，我尝试了一下抓包，在preupload之后会有一个https://member.bilibili.com/x/web/archive/tags的请求，参数分别是typeid，title，filename，desc，cover我尝试了一下只传一个参数title就可以获得一个包含推荐的标签的json数据

完整的url：https://member.bilibili.com/x/web/archive/tags?typeid=&title=名侦探柯南&filename=&desc=&cover=

另外，之前提到的稿件说明250字的限制，通过抓包发现提交的时候会有一个desc_format_id的参数，默认的是0,应该是通过对应的分区有不同的数值，目前我只知道选择单机游戏分区的时候，desc_format_id=29，稿件说明可以2000字

**Comment by comwrg** [comment]
`推荐标签`也是要让人选的吧，最多可以有10个标签，而`推荐标签`远大于十个。

**Comment by Kiritomo** [comment]
好吧，我这边自己处理一下吧
