### ISSUE TITLE
Upload ERROR

### ISSUE THREAD

**Issue by vbonluk** [comwrg/bilibiliUpload#5]
`<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 26080279 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 3 1
<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 26079289 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 3 2
<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 23657969 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 3 3
<br />
<b>Notice</b>:  Undefined index: chunk_paths in <b>/data/app/bvcflow_container/lib/Upload3.php</b> on line <b>77</b><br />
{"OK":0,"info":"Chunks error, should be 0"}
b'{"code":21001,"message":"\xe5\x8f\x82\xe6\x95\xb0\xe9\x94\x99\xe8\xaf\xaf","ttl":1}'`

please help~

**Comment by comwrg** [comment]
你用PHP调用的吗

**Comment by vbonluk** [comment]
不是的，我也是Python调用的。尝试了很多次，还是这个结果，Python3.6，编译器:pycharm，请问有遇到过吗？我这一直卡在这这里了。上网查也找不到方法才来这里这issue的。

**Comment by comwrg** [comment]
python调用的咋有<b></b>这种东西

**Comment by vbonluk** [comment]
😱我这是控制台输出的。我也。。。不知道。。。为何。。。会有。。。

**Comment by comwrg** [comment]
en.....

**Comment by vbonluk** [comment]
我发现哟将chunk size改大点会少两句报错😇，不知道是什么原因了

**Comment by comwrg** [comment]
我等会试下

**Comment by vbonluk** [comment]
好的，有什么需要我配合的尽管说就行了

**Comment by comwrg** [comment]
我刚才上传了下，可以上传
试下这个代码， 搞个小点的视频试下
```python
if __name__ == '__main__':
    b = Bilibili()
    r = b.login(username, password)
    print('login result:', r)
    b.upload(your video path, 'title', 37, 'tag', 'desc')
```

**Comment by huhugiter** [comment]
我重新试了一下，发现依旧会报错
`<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 26211789 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 5 1
`
但是前天的时候没有出现，不知道是不是b站的锅

**Comment by huhugiter** [comment]
我重新看了下form-data
```
4194304
------WebKitFormBoundarytOAObqHqbGtyfUb3
Content-Disposition: form-data; name="file"; filename="blob"
Content-Type: application/octet-stream
```
他们似乎把文件名都改为了blob。
修改140行为：
```python
('file', ('blob', chunks_data, 'video/mp4')),
```
否则报错
```
{"OK":-1,"info":"No file in body."} 11 1
```
之后。修改了
```python
CHUNK_SIZE = 4 * 1024 * 1024
```
因为算了后浏览器似乎是这个大小，不确定改变这个大小有什么影响
这样之后就可以成功上传了
```
{"OK": 1, "info": "Successful."} 11 1
```
另外我用的Chrome抓包，不确定是否和浏览器有关

**Comment by comwrg** [comment]
CHUNK_SIZE 是每次上传块的大小，我抓的包是每次10MB
然后文件名的我就不懂了

**Comment by vbonluk** [comment]
{"OK": 1, "info": "Successful."} 8 1
{"OK": 1, "info": "Successful."} 8 2
{"OK": 1, "info": "Successful."} 8 3
{"OK": 1, "info": "Successful."} 8 4
{"OK": 1, "info": "Successful."} 8 5
{"OK": 1, "info": "Successful."} 8 6
{"OK": 1, "info": "Successful."} 8 7
{"OK": 1, "info": "Successful."} 8 8
{"OK": 1, "info": "Successful."}
b'{"code":21001,"message":"\xe5\x8f\x82\xe6\x95\xb0\xe9\x94\x99\xe8\xaf\xaf","ttl":1}'

应该是上传成功了。但是我登录进去bilibili却没有是什么回事？?

**Comment by comwrg** [comment]
用最新的代码试试吧

**Comment by deng47** [comment]
把\xe5\x8f\x82\xe6\x95\xb0\xe9\x94\x99\xe8\xaf\xaf放[在线编码解码器](http://bianma.911cha.com/)
结果是‘参数错误’，应该是你最后post的json中有错误

**Comment by deng47** [comment]
` error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 26211789 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 5 1`
这个错误我之前也遇过，我尝试把CHUNK_SIZE改小，然而有出现类似
`{"OK":-1,"info":"No file in body."} 11 1`
的错误
最后发现似乎是文件名的问题（不知道为什么），因为我上传的是日语文件名，改成英文字母文件名就没有问题了

**Comment by huhugiter** [comment]
我稍微修改了一下，可以看看，不过我是按照我的情况来的，也许有不同的情况
https://gist.github.com/huhugiter/8d2b4baf96a6261a43ffca15f307ef38
另外cover_up也要加上csrf了,不然参数错误
```python
r = self.session.post(
        url='https://member.bilibili.com/x/vu/web/cover/up',
        data={
            'cover': b'data:image/jpeg;base64,' + (base64.b64encode(f.read()))
            'csrf': self.csrf,
        }
)
```

**Comment by vbonluk** [comment]
终于。。上传成功了。但是还是报错：

<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 26080103 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 3 1
<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 26079115 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 3 2
<br />
<b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 23657797 bytes) in <b>/data/app/bvcflow_container/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php</b> on line <b>173</b><br />
 3 3
<br />
<b>Notice</b>:  Undefined index: chunk_paths in <b>/data/app/bvcflow_container/lib/Upload3.php</b> on line <b>77</b><br />
{"OK":0,"info":"Chunks error, should be 0"}
b'{"code":0,"data":{"aid":15508891},"message":"0","ttl":1}'

**Comment by huhugiter** [comment]
@vbonluk 
试试添加这个
```python
while r.status_code == 504:
    print('Chunk: %s丨Result: 504丨Upload Again' % chunks_index)
    r = self.session.post(url_upload, files=upload_file)
```
或者直接
```python
while not re.search('Successful', r.text):
    print(r.text)
    print('Chunk: %s丨Result: Failed丨Upload Again' % chunks_index)
    r = self.session.post(url_upload, files=upload_file)
```
我记得这种情况返回504，应该是b站的锅，需要重新上传这一个CHUNK
可能这个CHUNK会上传失败很多次，最后反正会成功的，变量名可能不一样，要自己修改一下。

**Comment by vbonluk** [comment]
我继续按照你上面楼层的办法：

修改140行为：

('file', ('blob', chunks_data, 'video/mp4')),
否则报错

{"OK":-1,"info":"No file in body."} 11 1
之后。修改了

CHUNK_SIZE = 4 * 1024 * 1024

发现这样设置参数后比较正常了。下面是log：

{"OK": 1, "info": "Successful."} 8 1
{"OK": 1, "info": "Successful."} 8 2
{"OK": 1, "info": "Successful."} 8 3
{"OK": 1, "info": "Successful."} 8 4
{"OK": 1, "info": "Successful."} 8 5
{"OK": 1, "info": "Successful."} 8 6
{"OK": 1, "info": "Successful."} 8 7
{"OK": 1, "info": "Successful."} 8 8
{"OK": 1, "info": "Successful."}
b'{"code":0,"data":{"aid":15509259},"message":"0","ttl":1}'

请问这样算是正常的吗？

**Comment by huhugiter** [comment]
@vbonluk 
看输出应该是没问题了，b站投稿那里应该会有显示
另外我后面重新看了，似乎改为：
```python
('file', ('blob', chunks_data, 'application/octet-stream')),
```
会更好一点，毕竟原本抓包就是application/octet-stream

**Comment by vbonluk** [comment]
对了，我刚刚看了一下你的源码，我发现里面的登录运用的不错。作者这里是引用了外部的登录接口，我怕不安全。我看了一下你的，估计你是读取浏览器cookie来获取是是吗？我这里按照你的来尝试了一下，发现报错了。。我只引用了两个方法：isLogin和login_from_cookie。
报错如下：

AttributeError: 'NoneType' object has no attribute 'group'

应该是这里就开始错误了：

self.mid = re.search('DedeUserID=(.*?);', self.headers['Cookie'] + ';').group(1)

请问怎么处理的呢？

这是这样写的：

class Bilibili:
    def __init__(self):
        self.session = requests.session()
        self.login_from_cookie()

        if not self.isLogin():
            exit(0)

    def isLogin(self):
        response = self.session.get('https://api.bilibili.com/nav')
        info = response.json()
        status = info.get('data', None)
        if status:
            status = status.get('isLogin', None)
            print('isLogin: %s' % status)
            if status:
                return True
        else:
            print(status)
            return False

    def login_from_cookie(self):
        self.headers = {
            'Access-Control-Allow-Origin': '*',
        }

        self.headers['Cookie'] = COOKIE
        self.session.headers = self.headers

        self.mid = re.search('DedeUserID=(.*?);', self.headers['Cookie'] + ';').group(1)
        self.csrf = re.search('bili_jct=(.*?);', self.headers['Cookie'] + ';').group(1)
        self.session.headers['Accept'] = 'application/json, text/javascript, */*; q=0.01'
        self.session.headers['Referer'] = 'https://space.bilibili.com/{mid}/#!/'.format(mid=self.mid)

调用：

bili.login_from_cookie()

**Comment by huhugiter** [comment]
@vbonluk 
我刚刚重新试了一下，是可以的，可能你粘贴cookie没有粘贴全？

**Comment by vbonluk** [comment]
@huhugiter 还是不行的。我复制应该没问题的。我是Python3.6 + pycharm编译器 + Mac系统的。的确报错哦。

File "/Users/Vbon/Documents/videoporter_sourceTree/bilibili.py", line 50, in login_from_cookie
    self.mid = re.search('DedeUserID=(.*?);', self.headers['Cookie'] + ';').group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by vbonluk** [comment]
![wx20171018-182218](https://user-images.githubusercontent.com/7578155/31751360-8ac80cf4-b44a-11e7-8fde-8f2c2b2ef03a.png)

@huhugiter 
我看了一下，实在觉得这个COOKIE变量一直为空的。
我就怪了。你那里可以的？COOKIE在哪里赋值了呢？？

**Comment by huhugiter** [comment]
在最后
```python
if __name__ == '__main__':
    COOKIE = ''
    CHUNK_SIZE = 4 * 1024 * 1024
    main()
```
粘贴首页的cookie

**Comment by vbonluk** [comment]
@huhugiter 可以了十分感谢哦。建议作者@comwrg 也采用这种方法安全一点吧。不用每次去请求外部API：https://api.kaaass.net/biliapi/user/login

**Comment by deng47** [comment]
不大懂不安全具体是什么意思
如果用复制粘贴cookies的方法，每次过期都要重新复制粘贴，不会有点麻烦吗

**Comment by vbonluk** [comment]
@deng47 我也用了一段时间了。。。不过这个API我查看过他主页。API作者估计不会做坏事吧。还好。不过我觉得还是不请求外部的好，万一哪一天这接口被劫持了呢(虽然可能性小。。)。

**Comment by vbonluk** [comment]
或者说大伙有没有获取到官方的登录API接口并加以识别验证码或者验证滑动图片的方法呢？咋们可以研究一下如何处理它

**Comment by comwrg** [comment]
嗯, 最开始的时候我就是用cookie, 抓包的时候感觉好麻烦, 就查了下bilibili的登录, 就只有这唯一的一个API, 也就用了

**Comment by comwrg** [comment]
嗯, 最开始的时候我就是用cookie, 抓包的时候感觉好麻烦, 就查了下bilibili的登录, 就只有这唯一的一个API, 也就用了

**Comment by comwrg** [comment]
网页版的有滑动验证码, 手机端的有加密参数, 需要反编译
感觉都很有难度

**Comment by deng47** [comment]
我比较菜也比较懒，反正b站绑了手机，改一个独立密码不被人拿起撞库就算了

**Comment by vbonluk** [comment]
{"OK": 1, "info": "Successful."} 7 1
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/Vbon/Documents/videoporter_sourceTree/YoutubeHtmlVideoCatch.py", line 351, in <module>
    catch.parsehtml(catch.downloadpage(video_init_url), currentUrl=video_init_url)
  File "/Users/Vbon/Documents/videoporter_sourceTree/YoutubeHtmlVideoCatch.py", line 114, in parsehtml
    self.upLoad_video_auto()
  File "/Users/Vbon/Documents/videoporter_sourceTree/YoutubeHtmlVideoCatch.py", line 299, in upLoad_video_auto
    self.bilibili_upload(unUpload_url=unUpload_url)
  File "/Users/Vbon/Documents/videoporter_sourceTree/YoutubeHtmlVideoCatch.py", line 336, in bilibili_upload
    no_reprint=no_reprint)
  File "/Users/Vbon/Documents/videoporter_sourceTree/bilibili.py", line 185, in upload
    r = self.session.post(url, files=file)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

报错了。。。我是不是被封了。。你们的还可以不

**Comment by vbonluk** [comment]
简单点吧：

{"OK": 1, "info": "Successful."} 7 1

ConnectionResetError: [Errno 54] Connection reset by peer

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))


requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

就这3

**Comment by vbonluk** [comment]
额。。。问题找到了。。。是tag的中文字符问题。这。。。。

**Comment by vbonluk** [comment]
问题还是会出现；

我一开始以为是session会话没有close的问题，在上传完毕后加了句：

`      # 关闭session连接
        self.session.close()`

还是会上传失败。这是为何呢？我这里使用的是循环上传文件夹里面的文件。

log：

BrokenPipeError: [Errno 32] Broken pipe

**Comment by deng47** [comment]
试试更新你机器上的openssl

**Comment by vbonluk** [comment]
isLogin: True
{"OK": 1, "info": "Successful."} 17 1
{"OK": 1, "info": "Successful."} 17 2
{"OK": 1, "info": "Successful."} 17 3
{"OK": 1, "info": "Successful."} 17 4
{"OK": 1, "info": "Successful."} 17 5
{"OK": 1, "info": "Successful."} 17 6
{"OK": 1, "info": "Successful."} 17 7
{"OK": 1, "info": "Successful."} 17 8
BrokenPipeError 错误
重新上传：前10最美麗的狗品種混合物 | 中文字幕.mkv
{"OK": 1, "info": "Successful."} 17 1
{"OK": 1, "info": "Successful."} 17 2
{"OK": 1, "info": "Successful."} 17 3
{"OK": 1, "info": "Successful."} 17 4
{"OK": 1, "info": "Successful."} 17 5
BrokenPipeError 错误
重新上传：前10最美麗的狗品種混合物 | 中文字幕.mkv
{"OK": 1, "info": "Successful."} 17 1
{"OK": 1, "info": "Successful."} 17 2
{"OK": 1, "info": "Successful."} 17 3
{"OK": 1, "info": "Successful."} 17 4
{"OK": 1, "info": "Successful."} 17 5
{"OK": 1, "info": "Successful."} 17 6
{"OK": 1, "info": "Successful."} 17 7
{"OK": 1, "info": "Successful."} 17 8
{"OK": 1, "info": "Successful."} 17 9
{"OK": 1, "info": "Successful."} 17 10
{"OK": 1, "info": "Successful."} 17 11
{"OK": 1, "info": "Successful."} 17 12
{"OK": 1, "info": "Successful."} 17 13
{"OK": 1, "info": "Successful."} 17 14
{"OK": 1, "info": "Successful."} 17 15
{"OK": 1, "info": "Successful."} 17 16
BrokenPipeError 错误
重新上传：前10最美麗的狗品種混合物 | 中文字幕.mkv
{"OK": 1, "info": "Successful."} 17 1
{"OK": 1, "info": "Successful."} 17 2
{"OK": 1, "info": "Successful."} 17 3
{"OK": 1, "info": "Successful."} 17 4
{"OK": 1, "info": "Successful."} 17 5
BrokenPipeError 错误
重新上传：前10最美麗的狗品種混合物 | 中文字幕.mkv
{"OK": 1, "info": "Successful."} 17 1
{"OK": 1, "info": "Successful."} 17 2
{"OK": 1, "info": "Successful."} 17 3
{"OK": 1, "info": "Successful."} 17 4
{"OK": 1, "info": "Successful."} 17 5
{"OK": 1, "info": "Successful."} 17 6
{"OK": 1, "info": "Successful."} 17 7
{"OK": 1, "info": "Successful."} 17 8
{"OK": 1, "info": "Successful."} 17 9
{"OK": 1, "info": "Successful."} 17 10
{"OK": 1, "info": "Successful."} 17 11
{"OK": 1, "info": "Successful."} 17 12
{"OK": 1, "info": "Successful."} 17 13
{"OK": 1, "info": "Successful."} 17 14
{"OK": 1, "info": "Successful."} 17 15
{"OK": 1, "info": "Successful."} 17 16
{"OK": 1, "info": "Successful."} 17 17
{"OK": 1, "info": "Successful."}
上传成功！

我写了一个循环来执行。解决了上传中断导致程序crash的问题。

**Comment by vbonluk** [comment]
我已经commit了。大伙可以看看有无问题呗。

**Comment by xinxianren** [comment]
from bilibiliupload import *

b = Bilibili()
b.login(user='15558131972', pwd='123456xx')


import time
parts = VideoPart(path=r'/Users/macbookair/Desktop/friut vergitble/Oxford Phonics World 1 - The Alphabet - Letter Aa-M1SBbcdh5Sg.mp4', title='我是视频标题', desc='我是视频介绍')
title = '123456'  # str 标题
tid = 27   # int 视频类型，即分类  
ticks = time.time()  # 获取当前时间时间戳
new_ticks = str(ticks).split('.')[0]
tag = ['儿童英语', '少儿英语','英语启蒙','英语儿歌','简单儿歌']   # list 视频标签
desc = '我是一首英语歌' # str 注: 视频描述最大长度 250，超过长度B站服务器会报错
cover = 'http://i0.hdslb.com/bfs/archive/fed25ed2877d3a68bea43941ecbf563d920520af.jpg' # 封面地址，需使用 cover_up 方法获取
# source = '' # (str) – (optional) 转载地址
# no_reprint =  # (int) – (optional) 0=可以转载, 1=禁止转载(default)
# open_elec =  # (int) – (optional) 1=启用充电面板(默认) 0=禁止
# max_retry=  # (int) – (optional) max retry times per chunk


b.upload(parts=parts, title=title, tid=tid, tag=tag, desc=desc, source='', cover=cover, no_reprint=1, dtime=new_ticks, open_elec=0, max_retry=500)




------------《一下报错信息》---------------------

Exception                                 Traceback (most recent call last)
<ipython-input-33-cdadfd9d6677> in <module>
     14 
     15 
---> 16 b.upload(parts=parts, title=title, tid=tid, tag=tag, desc=desc, source='', cover=cover, no_reprint=1, dtime=new_ticks, open_elec=0, max_retry=500)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bilibiliupload/bilibili.py in upload(self, parts, title, tid, tag, desc, source, cover, no_reprint, dtime, open_elec, max_retry)
    348             raise Exception('Add video reach max retry times.')
    349 
--> 350         r = retry_add()
    351         return r.json()
    352 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bilibiliupload/bilibili.py in retry_add()
    343                     log.info('retry add video {}/{}, {}'.format(i, max_retry, r.text))
    344                 else:
--> 345                     raise Exception('Fail to add video, {}'.format(r.text))
    346                 log.info('sleep %ds', 5 * i)
    347                 time.sleep(5 * i)

Exception: Fail to add video, {"code":21001,"message":"参数错误","ttl":1}

**Comment by xinxianren** [comment]
不知道是什么问题

**Comment by xinxianren** [comment]
这问题怎么解决

**Comment by xinxianren** [comment]
已经搞定，只要不传时间戳上去就可以了
