### ISSUE TITLE
登录模块出错

### ISSUE THREAD

**Issue by jackforlit** [comwrg/bilibiliupload#54]
**Describe the bug**
登录模块出错，出现以下错误信息。
不知道是我一个的问题，还是大家都有。

**Your code**
b = Bilibili()
file = bilibili.VideoPart(L[0])
b.login(user, pwd)

**Debug log**

```
    b.login(user, pwd)
  File "C:\Users\Administrator\PycharmProjects\Hamal_release\venv\lib\site-packages\bilibiliupload\bilibili.py", line 159, in login
    raise Exception(r.text)
Exception: {"code":-3,"message":"API sign invalid","ts":1585125136}
```

**Video uploaded**
If possible please upload video to cloud disk and paste URL here.

**Error message**
```
# Paste error message here if has.
```

**Comment by jackforlit** [comment]
今天又试了下，现在好了。。。难道是接口不稳定？

**Comment by sqy941013** [comment]
今天也登不上了

**Comment by jackforlit** [comment]
现在错误信息如下
Exception: {"code":-449,"message":"服务繁忙，请稍后再试","ts":1586089998}

**Comment by mirrorhanyu** [comment]
本地可以成功登录，在 remote server 不能登录成功
```
Exception: {"code":-449,"message":"服务繁忙，请稍后再试","ts":1586089998}
```

**Comment by sqy941013** [comment]
我在洛杉矶的服务器没法登陆，本地可以登陆。用本地的服务器搭了ss-server，远程用soskcs5登陆就可以了。猜测应该是封锁了国外的IP？

**Comment by mirrorhanyu** [comment]
> 我在洛杉矶的服务器没法登陆，本地可以登陆。用本地的服务器搭了ss-server，远程用soskcs5登陆就可以了。猜测应该是封锁了国外的IP？

有可能。
在另外一个 repo 看到，有回复说是 [登录失败是因为好像v2接口改v3了](https://github.com/Dawnnnnnn/bilibili-live-tools/issues/249)，也可以尝试下。

**Comment by jackforlit** [comment]
今天还有以下这个错误。。。
  File "lib\site-packages\bilibiliupload\bilibili.py", line 163, in login
KeyError: 'cookie_info'

**Comment by mirrorhanyu** [comment]
亲测，把 v2 接口改成 v3，可正常使用。
目前把 bilibiliupload 源码 copy 到项目中，修改了 login 部分代码，修改可以参考 [bilibili-live-tools 源码](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/master/login.py)

希望作者能尽快更新，或者有时间我过几天提个 PR。

**Comment by jackforlit** [comment]
@mirrorhanyu 就是换成一下url就行了？得空我试试

url = "https://passport.snm0516.aisee.tv/api/tv/login"

**Comment by mirrorhanyu** [comment]
不是的，需要整体修改 login 方法。
参考上面贴的 [bilibili-live-tools 源码](https://github.com/Dawnnnnnn/bilibili-live-tools/blob/master/login.py)。最终保证 bilibiliupload/bilibili.py 里 login 方法的结尾
```
self.session.headers["cookie"] = 
self.csrf = 
self.mid = 
self.session.headers['Accept'] = 
self.session.headers['Referer'] = 
```
塞入正确的值就好了

**Comment by jackforlit** [comment]
@mirrorhanyu 老哥，直接把你改的贴上来吧

**Comment by jackforlit** [comment]
@comwrg 多谢，老大，已验证。
