### ISSUE TITLE
放一个测试过成功的代码,附加我分析的一份上传协议分析

### ISSUE THREAD

**Issue by daofeng2015** [comwrg/bilibiliupload#59]
`from bilibiliupload import * 
b = Bilibili()
login_status = b.login("user","pwd")
print(login_status)
video = VideoPart('1.mp4',title='123',desc='23333')
tags = {u"123", u"Shroud", u"Beaulo"}
b.upload(parts=video, title="153 title", tid=65,tag=tags,desc="upload from 2333",source='http://www.youtube.com')`
[bilibili上传协议分析.txt](https://github.com/comwrg/bilibiliupload/files/4572750/bilibili.txt)

**Comment by crashiers** [comment]
缩略图是哪个参数，目前没有缩略图的

**Comment by daofeng2015** [comment]
> 缩略图是哪个参数，目前没有缩略图的

是不是投稿的封面?封面的参数是cover这个

**Comment by crashiers** [comment]
可以做个专栏投稿的功能
